spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/volunteers_control;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: lu
    password:
  jpa:
    hibernate:
      ddl-auto: update